# Generated by Django 6.0.6 on 2026-07-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_name',
            field=models.CharField(default='Lab A', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
