# Generated by Django 6.0.6 on 2026-07-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lab_lab_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='lab_name',
        ),
    ]
